### ISSUE TITLE
clarification on the `get_mean` function in the experiment.py script.

### ISSUE THREAD

**Issue by sarsanaee** [shenango/all#2]
Hi

Would you please explain what the following snippet does? In particular, why do you multiply the target value with other values (83.89, 59.37, 78.0, 65.0)?

```
    return int(float(target_us) * {
        ('rust', True): 83.89,
        ('rust', False): 59.37,
        ('cpp', True): 78.0,
        ('cpp', False): 65.0,
    }.get((impl, noht)))
```

I'm probably missing something, but it would be great if you could explain this.

Thanks.

**Comment by joshuafried** [comment]
Hello, thanks for the question. This function calculates the number of iterations of fake work that should be performed for each request in order to achieve an average service time of target_us. These numbers were profiled on the machines that we used for our evaluation. So, for example, 83.89 iterations takes 1 microsecond in our rust synthetic application (used for Figure 4 in the paper) when hyperthreading is enabled.

**Comment by sarsanaee** [comment]
Makes sense. I was gonna exactly use 1us, and then I was like, ok, then what is 83.89 :)) Thanks for the clear. But these values are not gonna be accurate for MY machine and I need to readjust them right?
